openapi: 3.2.0
info:
  title: CertifID V2 Location API
  description: Access to CertifID data and functions for 3rd Party Integrations
  version: v1
security:
- oauth2: []
tags:
- name: Location
paths:
  /api/v1/Account:
    get:
      tags:
      - Location
      summary: Retrieve the list of accounts that the customer has access to within CertifID's platform.
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CertifID.V2.PublicAPI.ViewModels.Locations.LocationViewModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CertifID.V2.PublicAPI.ViewModels.Locations.LocationViewModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CertifID.V2.PublicAPI.ViewModels.Locations.LocationViewModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - CertifIDUser
  /api/v1/Account/{id}:
    get:
      tags:
      - Location
      summary: Retrieve a specific account belonging to the customer within CertifID's platform.
      parameters:
      - name: id
        in: path
        description: The ID of the location/account to retrieve.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CertifID.V2.PublicAPI.ViewModels.Locations.LocationViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/CertifID.V2.PublicAPI.ViewModels.Locations.LocationViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/CertifID.V2.PublicAPI.ViewModels.Locations.LocationViewModel'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2:
        - CertifIDUser
components:
  schemas:
    CertifID.V2.PublicAPI.ViewModels.Locations.LocationViewModel:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the account.
        name:
          type: string
          description: The name given to identify the account/office by the customer within their organization.
          example: South Bank - Central Office
        companyId:
          type:
          - string
          - 'null'
          description: The ID of parent account that this child account is organized under within the
            customer's organization.
        isDefault:
          type: boolean
          description: A flag indicating whether the account is selected as the user's default.
      additionalProperties: false
      description: 'An account/location within the CertifID platform, often representing a single agency
        or office

        location within a customer''s organization.'
    Microsoft.AspNetCore.Mvc.ProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        instance:
          type:
          - string
          - 'null'
      additionalProperties: {}
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.certifid.com/authorize?audience=https://api.certifid.com&connection=CertifID-Users-DB
          tokenUrl: https://auth.certifid.com/oauth/token
          scopes: {}
